name: GC TESTS
run-name: GC TESTS
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: compile library
        run: |
          make -C ${{ github.workspace }}
      - name: compile test binary
        run: |
          make -C ${{ github.workspace }} test
      - name: basics tests
        run: |
          ./test
      - name: setup valgrind
        run: |
          sudo apt install -y valgrind
      - name: memory leaks tests
        run: |
          valgrind --leak-check=full ./test
